name: sellermultivendor
description: A new Flutter project.

publish_to: "none"
version: 2.10.2+23

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2  # Ensure it matches other dependencies
  firebase_core: ^3.11.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  http: ^1.3.0
  shared_preferences: ^2.0.11
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.3.1 
  collection: ^1.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.7
  flutter_html_to_pdf:
    git:
      url: https://github.com/mohammadhprp/flutter_html_to_pdf2
  sms_autofill: ^2.3.1
  # image_picker: ^1.0.1
  fl_chart: ^0.70.2
  file_picker: ^8.0.3
  sticky_headers: ^0.3.0+2
  html_editor_enhanced: ^2.5.1
  mime: ^2.0.0
  lottie: ^3.0.0
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.15.0
  flutter_widget_from_html: ^0.15.0
  provider: ^6.0.5
  google_maps_flutter: ^2.2.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  flutter_email_sender: ^7.0.0
  bloc: ^9.0.0
  intl_phone_field: ^3.1.0
  open_filex: ^4.3.2
  external_path: ^2.0.1
  path_provider: ^2.0.14
  flutter_local_notifications: ^18.0.1
  flutter_bloc: ^9.0.0
  dio: ^5.4.0
  permission_handler: ^11.2.1
  device_info_plus: ^11.3.0
  meta: any
  http_parser: any
  awesome_notifications: ^0.10.0
  video_player_web: ^2.3.4

dependency_overrides:
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  just_audio: ^0.9.30


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - lib/Language/
    - assets/images/PNG/
    - assets/images/SVG/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
