/**
 * Template chrome strings (nav labels, form labels, badge) in the five locale
 * codes the platform serves: uz (Uzbek latin), ru, en, tg (Tajik), ky (Kyrgyz).
 * Partner CONTENT is trilingual jsonb in the DB — these are only the fixed UI
 * strings around it. Every new key must be added to all five locales.
 */
export const UI = {
  uz: {
    home: "Bosh sahifa",
    news: "Yangiliklar",
    achievements: "Yutuqlar",
    about: "Biz haqimizda",
    admissions: "Qabul",
    contact: "Aloqa",
    readMore: "Batafsil",
    contactHeading: "Biz bilan bog‘laning",
    formName: "Ismingiz",
    formPhone: "Telefon raqamingiz",
    formMessage: "Xabar (ixtiyoriy)",
    formSubmit: "Yuborish",
    formThanks: "Rahmat! Tez orada siz bilan bog‘lanamiz.",
    formError: "Yuborilmadi. Iltimos, qayta urinib ko‘ring.",
    adminTitle: "Sayt boshqaruvi",
    postKindNews: "Yangilik",
    postKindAchievement: "Yutuq",
    postKindAnnouncement: "E’lon",
    fieldTitle: "Sarlavha",
    fieldBody: "Matn",
    publish: "E’lon qilish",
    remove: "O‘chirish",
    publishedOk: "E’lon qilindi! Sayt yangilandi.",
    translationsPending: "Tarjimalar keyinroq avtomatik qo‘shiladi.",
    recentPosts: "So‘nggi e’lonlar",
    poweredBy: "Powered by Aspira",
  },
  ru: {
    home: "Главная",
    news: "Новости",
    achievements: "Достижения",
    about: "О нас",
    admissions: "Приём",
    contact: "Контакты",
    readMore: "Подробнее",
    contactHeading: "Свяжитесь с нами",
    formName: "Ваше имя",
    formPhone: "Ваш телефон",
    formMessage: "Сообщение (необязательно)",
    formSubmit: "Отправить",
    formThanks: "Спасибо! Мы скоро свяжемся с вами.",
    formError: "Не удалось отправить. Пожалуйста, попробуйте ещё раз.",
    adminTitle: "Управление сайтом",
    postKindNews: "Новость",
    postKindAchievement: "Достижение",
    postKindAnnouncement: "Объявление",
    fieldTitle: "Заголовок",
    fieldBody: "Текст",
    publish: "Опубликовать",
    remove: "Удалить",
    publishedOk: "Опубликовано! Сайт обновлён.",
    translationsPending: "Переводы будут добавлены автоматически позже.",
    recentPosts: "Последние записи",
    poweredBy: "Powered by Aspira",
  },
  en: {
    home: "Home",
    news: "News",
    achievements: "Achievements",
    about: "About",
    admissions: "Admissions",
    contact: "Contact",
    readMore: "Read more",
    contactHeading: "Get in touch",
    formName: "Your name",
    formPhone: "Your phone",
    formMessage: "Message (optional)",
    formSubmit: "Send",
    formThanks: "Thank you! We will be in touch soon.",
    formError: "Could not send. Please try again.",
    adminTitle: "Site admin",
    postKindNews: "News",
    postKindAchievement: "Achievement",
    postKindAnnouncement: "Announcement",
    fieldTitle: "Title",
    fieldBody: "Text",
    publish: "Publish",
    remove: "Delete",
    publishedOk: "Published! The site is updated.",
    translationsPending: "Translations will be added automatically later.",
    recentPosts: "Recent posts",
    poweredBy: "Powered by Aspira",
  },
  tg: {
    home: "Саҳифаи асосӣ",
    news: "Хабарҳо",
    achievements: "Дастовардҳо",
    about: "Дар бораи мо",
    admissions: "Қабул",
    contact: "Тамос",
    readMore: "Муфассал",
    contactHeading: "Бо мо дар тамос шавед",
    formName: "Номи шумо",
    formPhone: "Телефони шумо",
    formMessage: "Паём (ихтиёрӣ)",
    formSubmit: "Фиристодан",
    formThanks: "Ташаккур! Ба зудӣ бо шумо тамос мегирем.",
    formError: "Фиристода нашуд. Лутфан, боз кӯшиш кунед.",
    adminTitle: "Идоракунии сомона",
    postKindNews: "Хабар",
    postKindAchievement: "Дастовард",
    postKindAnnouncement: "Эълон",
    fieldTitle: "Сарлавҳа",
    fieldBody: "Матн",
    publish: "Нашр кардан",
    remove: "Нест кардан",
    publishedOk: "Нашр шуд! Сомона нав шуд.",
    translationsPending: "Тарҷумаҳо баъдтар ба таври худкор илова мешаванд.",
    recentPosts: "Навиштаҳои охирин",
    poweredBy: "Powered by Aspira",
  },
  ky: {
    home: "Башкы бет",
    news: "Жаңылыктар",
    achievements: "Жетишкендиктер",
    about: "Биз жөнүндө",
    admissions: "Кабыл алуу",
    contact: "Байланыш",
    readMore: "Толугураак",
    contactHeading: "Биз менен байланышыңыз",
    formName: "Атыңыз",
    formPhone: "Телефонуңуз",
    formMessage: "Билдирүү (милдеттүү эмес)",
    formSubmit: "Жөнөтүү",
    formThanks: "Рахмат! Жакында сиз менен байланышабыз.",
    formError: "Жөнөтүлгөн жок. Кайра аракет кылып көрүңүз.",
    adminTitle: "Сайтты башкаруу",
    postKindNews: "Жаңылык",
    postKindAchievement: "Жетишкендик",
    postKindAnnouncement: "Кулактандыруу",
    fieldTitle: "Аталышы",
    fieldBody: "Текст",
    publish: "Жарыялоо",
    remove: "Өчүрүү",
    publishedOk: "Жарыяланды! Сайт жаңырды.",
    translationsPending: "Котормолор кийинчерээк автоматтык түрдө кошулат.",
    recentPosts: "Акыркы жазуулар",
    poweredBy: "Powered by Aspira",
  },
} as const;

export type UiLocale = keyof typeof UI;

export function ui(locale: string) {
  return UI[(locale in UI ? locale : "en") as UiLocale];
}

export const LOCALE_NAMES: Record<string, string> = {
  uz: "O‘zbekcha",
  ru: "Русский",
  en: "English",
  tg: "Тоҷикӣ",
  ky: "Кыргызча",
};
